name: Build executables

# Manually trigger this action
on: workflow_dispatch

env:
  CRATE_NAME: asfald
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release - ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          - os: windows
            name: windows-x64
            target: x86_64-pc-windows-msvc
            runs-on: windows-latest
            command: build
            extension: .exe
          - os: macos
            name: apple-arm64
            target: aarch64-apple-darwin
            runs-on: macos-14
            command: build
          - os: macos
            name: macos-x64
            target: x86_64-apple-darwin
            runs-on: macos-14
            command: build
          - os: FreeBSD-x86_64
            name: FreeBSD-x64
            runs-on: [ubuntu-latest]
            target: x86_64-unknown-freebsd
            command: build

          - os: linux
            name: linux-x64-musl
            target: x86_64-unknown-linux-musl
            runs-on: [ubuntu-latest]
            command: build
          # for linux we only build the statically linked executable
          #- os: linux
          #  name: linux-x64
          #  target: x86_64-unknown-linux-gnu
          #  runs-on: [ ubuntu-latest]
          #  command: build
          - os: linux
            name: linux-arm64-musl
            target: aarch64-unknown-linux-musl
            runs-on: [ubuntu-latest]
            command: build
          #- os: linux
          #  name: linux-arm64
          #  target: aarch64-unknown-linux-gnu
          #  runs-on: [ubuntu-latest]
          #  command: build
          - os: linux
            name: linux-armv7-musl
            target: armv7-unknown-linux-musleabi
            runs-on: [ubuntu-latest]
            command: build
          #- os: linux
          #  name: linux-armv7
          #  target: armv7-unknown-linux-gnueabi
          #  runs-on: [ubuntu-latest]
          #  command: build

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - run: ls target/${{matrix.platform.target}}/release/asfald${{matrix.platform.extension}}
      - name: Make artifact available
        uses: actions/upload-artifact@v4
        with:
          name: asfald-${{matrix.platform.target}}
          path: target/${{matrix.platform.target}}/release/asfald${{matrix.platform.extension}}
