name: Run tests

on:
  pull_request:

jobs:
  build:
    name: Run Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: make test
        shell: bash
        run: |
          make test
